SELECT* FROM CUSTOMER limit(10);

--Q1 total revenue generated by male vs female customer
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- Q2 Which customers used discount but still spent more than avg purchase amnt
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3 Which are the top 5 products with the highest avg review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4, Compare the avg purchase amount between Standard and Express Shipping

SELECT shipping_type,
AVG(purchase_amount)
FROM customer
WHERE shipping_type in ('Standard', 'Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare avg and total revenue between subscribers and non-subscribers.

SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- Q6 Which 5 products have the highest percentage of purchase with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

-- Q7 Are customers who are repeat buyers(>5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q8 What is revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

-- Q9 Segment customer into New, Returning, and Loyal based on their total 
-- number of previous purhases, and show the count of each segment.
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases Between 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)
SELECT customer_segment, count(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q10 What are the top 3 most purchased products within each category?
WITH item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category ORDER BY COUNT(customer_id) DESC) as item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
